global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']