version: '3'
services:
  mysql:
    image: public.ecr.aws/docker/library/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=project
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
    volumes:
      - ./backend/mysql/initData.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always