version: '3'
services:
  phpmyadmin:
    image: public.ecr.aws/docker/library/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=rootpw
    restart: always