version: '3'
services:
  fastapi:
    build: 
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - ENV_VAR_NAME=VALUE
    restart: always
  
  mysql:
    image: public.ecr.aws/docker/library/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=project
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
    volumes:
      - ./backend/mysql/initData.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  
  phpmyadmin:
    image: public.ecr.aws/docker/library/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=rootpw
    restart: always
  
  nginx:
    image: public.ecr.aws/nginx/nginx:mainline-alpine
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi
    restart: always
  
  prometheus:
    image: public.ecr.aws/bitnami/prometheus:latest
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: always
  
  node_exporter:
    image: public.ecr.aws/bitnami/node-exporter:latest
    ports:
      - "9100:9100"
    restart: always
  
  grafana:
    image: public.ecr.aws/bitnami/grafana:latest
    ports:
      - "3333:3333"
    depends_on:
      - prometheus
    restart: always