version: '3'
services:
  fastapi:
    build: 
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - ENV_VAR_NAME=VALUE
    restart: always
  
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=project
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
    volumes:
      - ./backend/mysql/initData.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=rootpw
    restart: always