version: '3'
services:
  fastapi:
    build: 
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR_NAME=VALUE
    restart: always