
export const  mockPet = {
    "petName": "Buddy",
    "species": "Dog",
    "breed": "Labrador",
    "age": 3,
    "gender": "Male",
    "weight": "25",
    "color": "Golden",
    "dateofbirth": "2020-03-15",
    "description": "Friendly and playful",
    "imageIDs": [],
    "features": {
        "feature1": true,
        "feature2": true,
        "feature3": true,
        "feature4": false,
        "feature5": true,
        "feature6": true,
        "feature7": true,
        "feature8": false,
        "feature9": true,
        "feature10": false,
        "feature11": false
    },
    "availabilityStatus": "Available",
    "vaccinationRecord": null,
    "shelterID": 501,
    "vaccinationName": [
        "Lyme Disease",
        "GOGO",
        "test"
    ],
    "vaccinationDate": [
        "2023-02-05",
        "2020-02-01",
        "2020-02-01"
    ],
    "name": "Happy Paws",
    "phone": "0823456789",
    "address": "123 Main St, City",
    "adoptionApplications": {}
}

export const defaultPets = [{
            petName: 'Max',
            species: 'Dog',
            breed: 'Labrador',
            age: 1,
            availabilityStatus: 'Available',
            imageIDs: [1],
            features: {
            feature1: true,
            feature2: false,
            feature3: true,
            feature4: false,
            feature5: true,
            feature6: false,
            feature7: false,
            feature8: false,
            feature9: false,
            feature10: false,
            feature11: false,
            },
            name: 'Happy Paws',
            phone: '0922607795',
            address: 'bangkok soi 1 thailand pathumwan'
        }, {
            petName: 'Max',
            species: 'Dog',
            breed: 'Shiba',
            availabilityStatus: 'Available',
            age: 5,
            imageIDs: [2],
            features: {
            feature1: true,
            feature2: false,
            feature3: true,
            feature4: false,
            feature5: true,
            feature6: false,
            feature7: false,
            feature8: false,
            feature9: false,
            feature10: false,
            feature11: false,
            },
            name: 'Hapy Paws',
            phone: '0922607795',
            address: '209 Mantika Bangbon 3 Rd. Bangbon Bnagkok 10150'
        },, {
            petName: 'Max',
            species: 'Dog',
            breed: 'Siba',
            availabilityStatus: 'Available',
            imageIDs: [2],
            features: {
            feature1: true,
            feature2: false,
            feature3: true,
            feature4: false,
            feature5: true,
            feature6: false,
            feature7: false,
            feature8: false,
            feature9: false,
            feature10: false,
            feature11: false,
            },
            name: 'Happy',
            phone: '0922607795',
            address: '209 Mantika Bangbon 3 Rd. Bangbon Bnagkok 10150'
        },
]